// Events: the id a gateway re-derives and the signature it checks.
//
// Every event this gateway trusts arrives off a relay — a member's Provider
// Profile, a standby's Takeover — so the fixtures generated by the provider
// are the ground truth here: if this file disagrees with them, this file is
// wrong. A gateway signs nothing, so `signEvent` is a test helper and is
// tested as one.

import { strict as assert } from 'node:assert';
import { describe, it } from 'node:test';
import { readFileSync } from 'node:fs';

import { eventId, serializeEvent, verifyEvent } from '../src/nostr.mjs';
import { publicKeyOf, signEvent } from './helpers/sign.mjs';

const fixture = (name) =>
  JSON.parse(readFileSync(new URL(`./fixtures/wire/${name}.json`, import.meta.url), 'utf8'));

const profile = fixture('directory.profile');
const takeover = fixture('directory.takeover');
const constants = fixture('constants');

describe('serializeEvent', () => {
  it('reproduces the fixture NIP-01 serialization byte for byte', () => {
    assert.equal(serializeEvent(profile.event), profile.nip01_serialization);
  });
});

describe('eventId', () => {
  it('re-derives the fixture Profile id', () => {
    assert.equal(eventId(profile.event), profile.event.id);
  });
});

describe('verifyEvent', () => {
  it('accepts the provider-signed Profile the provider generated', () => {
    assert.equal(verifyEvent(profile.event), true);
  });

  it('refuses an event whose content was changed after signing', () => {
    const tampered = { ...profile.event, content: profile.event.content.replace('203.0', '198.51') };
    assert.equal(verifyEvent(tampered), false);
  });

  it('refuses an event carrying an id that is not its own', () => {
    assert.equal(verifyEvent({ ...profile.event, id: 'f'.repeat(64) }), false);
  });

  it('refuses a signature by another key', () => {
    const impostor = { ...profile.event, sig: takeover.event.sig };
    assert.equal(verifyEvent(impostor), false);
  });

  it('refuses a malformed event rather than throwing', () => {
    assert.equal(verifyEvent(null), false);
    assert.equal(verifyEvent({ kind: constants.kinds.K_PROFILE }), false);
    assert.equal(verifyEvent({ ...profile.event, sig: 'not hex' }), false);
  });
});

describe('publicKeyOf', () => {
  it('derives the fixture keys', () => {
    assert.equal(publicKeyOf(constants.provider.secret_key), constants.provider.public_key);
    assert.equal(publicKeyOf(constants.standby_provider.secret_key), constants.standby_provider.public_key);
  });

  it('refuses something that is not a 32-byte secret key', () => {
    assert.throws(() => publicKeyOf('abc'), /64 hex/);
  });
});

describe('signEvent', () => {
  it('signs an event this gateway can then verify', () => {
    const signed = signEvent(constants.provider.secret_key, {
      kind: constants.kinds.K_PROFILE,
      created_at: 1700000000,
      tags: [['L', constants.label]],
      content: '{}',
    });
    assert.equal(signed.pubkey, constants.provider.public_key);
    assert.equal(signed.id, eventId(signed));
    assert.equal(verifyEvent(signed), true);
  });
});
