// Events: the id a gateway re-derives and the signature it checks.
//
// Everything this gateway trusts arrives as a signed event off a relay, so the
// fixtures generated by the provider are the ground truth here: if this file
// disagrees with them, this file is wrong.

import { strict as assert } from 'node:assert';
import { describe, it } from 'node:test';
import { readFileSync } from 'node:fs';

import { eventId, publicKeyOf, serializeEvent, signEvent, verifyEvent } from '../src/nostr.mjs';

const fixture = (name) =>
  JSON.parse(readFileSync(new URL(`./fixtures/wire/${name}.json`, import.meta.url), 'utf8'));

const grant = fixture('gateway_grant');
const constants = fixture('constants');

describe('serializeEvent', () => {
  it('reproduces the fixture NIP-01 serialization byte for byte', () => {
    assert.equal(serializeEvent(grant.event), grant.nip01_serialization);
  });
});

describe('eventId', () => {
  it('re-derives the fixture grant id', () => {
    assert.equal(eventId(grant.event), grant.event.id);
  });
});

describe('verifyEvent', () => {
  it('accepts the tenant-signed grant the provider generated', () => {
    assert.equal(verifyEvent(grant.event), true);
  });

  it('refuses an event whose content was changed after signing', () => {
    const tampered = { ...grant.event, content: grant.event.content.replace('443', '8443') };
    assert.equal(verifyEvent(tampered), false);
  });

  it('refuses an event carrying an id that is not its own', () => {
    assert.equal(verifyEvent({ ...grant.event, id: 'f'.repeat(64) }), false);
  });

  it('refuses a signature by another key', () => {
    const other = fixture('error.bad_grant').request_body.request.content;
    const impostor = { ...grant.event, sig: JSON.parse(other).grant.sig };
    assert.equal(verifyEvent(impostor), false);
  });

  it('refuses a malformed event rather than throwing', () => {
    assert.equal(verifyEvent(null), false);
    assert.equal(verifyEvent({ kind: 30438 }), false);
    assert.equal(verifyEvent({ ...grant.event, sig: 'not hex' }), false);
  });
});

describe('publicKeyOf', () => {
  it('derives the fixture keys', () => {
    assert.equal(publicKeyOf(constants.gateway.secret_key), constants.gateway.public_key);
    assert.equal(publicKeyOf(constants.tenant.secret_key), constants.tenant.public_key);
  });

  it('refuses something that is not a 32-byte secret key', () => {
    assert.throws(() => publicKeyOf('abc'), /64 hex/);
  });
});

describe('signEvent', () => {
  it('signs an event this gateway can then verify, at its own key', () => {
    const signed = signEvent(constants.gateway.secret_key, {
      kind: constants.kinds.K_LEASE_REQUEST,
      created_at: 1700000000,
      tags: [['op', 'status']],
      content: '{}',
    });
    assert.equal(signed.pubkey, constants.gateway.public_key);
    assert.equal(signed.id, eventId(signed));
    assert.equal(verifyEvent(signed), true);
  });
});
